=== abcdefghiklk/fixit/aspectj/org.aspectj/modules/tests/ajcTestSuite.dtd
<!-- this defines a DOCTYPE for a suite of ajc tests -->
<!-- element-component mappings are in org.aspectj.testing.xml.AjcSpecXmlReader -->
<!-- element names are determined by the component XMLNAME static variable -->

   <!ELEMENT suite (ajc-test*)>
   <!ATTLIST suite suiteDir CDATA #IMPLIED >
	<!-- permits leading inc-compile, will fail -->
   <!ELEMENT ajc-test ((compile | inc-compile | run)*)>
   <!ATTLIST ajc-test title CDATA #REQUIRED >
   <!ATTLIST ajc-test dir CDATA #REQUIRED >
   <!ATTLIST ajc-test pr CDATA #IMPLIED >
   <!ATTLIST ajc-test keywords CDATA #IMPLIED >
   <!ATTLIST ajc-test comment CDATA #IMPLIED >

   <!ELEMENT compile (dir-changes*,message*)>
   <!ATTLIST compile staging CDATA #IMPLIED >
   <!ATTLIST compile badInput CDATA #IMPLIED >
   <!ATTLIST compile files CDATA #IMPLIED >
   <!ATTLIST compile reuseCompiler CDATA #IMPLIED >
   <!ATTLIST compile includeClassesDir CDATA #IMPLIED >
   <!ATTLIST compile argfiles CDATA #IMPLIED >
   <!ATTLIST compile aspectpath CDATA #IMPLIED >
   <!ATTLIST compile classpath CDATA #IMPLIED >
   <!ATTLIST compile extdirs CDATA #IMPLIED >
   <!ATTLIST compile options CDATA #IMPLIED >
   <!ATTLIST compile sourceroots CDATA #IMPLIED >
   <!ATTLIST compile xlintfile CDATA #IMPLIED >
   <!ATTLIST compile outjar CDATA #IMPLIED >

   <!ELEMENT inc-compile (dir-changes*,message*)>
   <!ATTLIST inc-compile tag CDATA #REQUIRED >
   <!ATTLIST inc-compile fresh CDATA #IMPLIED >
   <!ATTLIST inc-compile checkModel CDATA #IMPLIED >

   <!ELEMENT run (dir-changes*,message*)>
   <!ATTLIST run class CDATA #REQUIRED >
   <!ATTLIST run skipTester CDATA #IMPLIED >
   <!ATTLIST run vm CDATA #IMPLIED >
   <!ATTLIST run options CDATA #IMPLIED >
   <!ATTLIST run errStreamIsError CDATA #IMPLIED >
   <!ATTLIST run outStreamIsError CDATA #IMPLIED >
   <!ATTLIST run fork CDATA #IMPLIED >
   <!ATTLIST run vmargs CDATA #IMPLIED >
   <!ATTLIST run aspectpath CDATA #IMPLIED >
   <!ATTLIST run classpath CDATA #IMPLIED >
   <!ATTLIST run LTW CDATA #IMPLIED >
   <!ATTLIST run exception CDATA #IMPLIED >

   <!ELEMENT message (source*)>
   <!ATTLIST message kind (abort | fail | error | warning | info | Xlint) #REQUIRED >
   <!ATTLIST message line CDATA #IMPLIED >
   <!ATTLIST message text CDATA #IMPLIED >
   <!ATTLIST message file CDATA #IMPLIED >
   <!ATTLIST message details CDATA #IMPLIED >

   <!ELEMENT source (#PCDATA)>
   <!ATTLIST source line CDATA #IMPLIED >
   <!ATTLIST source file CDATA #IMPLIED >

   <!ELEMENT dir-changes (#PCDATA)>
   <!ATTLIST dir-changes dirToken (classes | run) #IMPLIED >
   <!ATTLIST dir-changes defaultSuffix (.class) #IMPLIED >
   <!ATTLIST dir-changes added CDATA #IMPLIED >
   <!ATTLIST dir-changes removed CDATA #IMPLIED >
   <!ATTLIST dir-changes updated CDATA #IMPLIED >
   <!ATTLIST dir-changes unchanged CDATA #IMPLIED >
   <!ATTLIST dir-changes expDir CDATA #IMPLIED >
   <!ATTLIST dir-changes fastFail CDATA #IMPLIED >
   <!ATTLIST dir-changes delay CDATA #IMPLIED >

=== abcdefghiklk/fixit/aspectj/org.aspectj/modules/tests/ajcTests10.xml
<!DOCTYPE suite SYSTEM "../tests/ajcTestSuite.dtd">


<suite>
    <ajc-test dir="jacks"
      title="14.20-label-11  The break is interrupted by the try-finally"
      keywords="from-stricttests">
        <compile options="-strict" files="FinallyReturns.java">
            <message kind="error" line="11"/>
        </compile>
    </ajc-test>

    <ajc-test dir="jacks"
      title="14.20-catch-14  The throw is interrupted by the inner finally"
      keywords="from-stricttests">
        <compile options="-strict" files="FinallyReturnsThrows.java">
            <message kind="error" line="10"/>
        </compile>
    </ajc-test>

    <ajc-test dir="jacks"
      title="14.20-label-12  The break is interrupted by the try-finally"
      keywords="from-stricttests">
        <compile options="-strict" files="FinallyReturnsBreakInCatch.java">
            <message kind="error" line="10"/>
        </compile>
    </ajc-test>
    
    <!-- strict-only tests treated as 1.0 tests -->

    <!-- ajc-only tests treated as 1.0 tests -->
    <ajc-test dir="new" pr="567"
      title="cyclic interface inheritance not detected if no classes implement the interfaces"
      keywords="from-java,purejava,messages-vary">
        <compile files="CyclicInterfaceInheritance.java" 
               options="!ajc">
            <message kind="error" line="14"/>
        </compile>
    </ajc-test>

    <ajc-test dir="new/packagePrefix" pr="574"
      title="classes that are package prefixes are illegal"
      keywords="from-java,purejava,messages-vary">
        <compile files="p/prefix.java,p/prefix/SomeClass.java"
               options="!ajc">
            <message kind="error" line="3"/>
        </compile>
    </ajc-test>

    <ajc-test dir="pureJava"
      title="suggested by Jacks 15.28-qualified-namestr tests"
      keywords="from-java,purejava,messages-vary">
        <compile files="NonConstants.java" 
               options="!ajc">
            <message kind="error" line="14"/>
            <message kind="error" line="15"/>
            <message kind="error" line="16"/>
        </compile>
    </ajc-test>

    <ajc-test dir="new" pr="643" title="try without catch or finally"
      keywords="from-java,purejava,message-vary">
        <compile files="TryNoCatchCE.java"
               options="!ajc">
            <message kind="error" line="5"/>
        </compile>
    </ajc-test>

    <ajc-test dir="new" pr="642" title="invalid floating-point constant"
      keywords="from-java,purejava,messages-vary">
        <compile files="ParsingFloatCE.java"
               options="!ajc">
            <message kind="error" line="5"/>
            <message kind="error" line="6"/>
        </compile>
    </ajc-test>

    <ajc-test dir="new/subaspects" pr="647"
      title="concrete aspect unable to access abstract package-private method in parent for overriding"
      keywords="from-java,purejava,messages-vary">
        <compile files="parent/ParentMethodCE.java,child/ChildMethodCE.java"
               options="!ajc">
            <message kind="error" line="27"/>
        </compile>
    </ajc-test>

    <ajc-test dir="new" pr="701"
      title="CE for ambiguous type reference (two type declarations)"
      keywords="from-java,purejava,messages-vary">
        <compile files="AmbiguousClassReference3CE.java"
               options="!ajc">
            <message kind="error" line="9"/>
            <message kind="error" line="10"/>
        </compile>
    </ajc-test>

    <ajc-test dir="new" pr="701"
      title="CE for ambiguous type reference (two inner types)"
      keywords="from-java,purejava,messages-vary">
        <compile files="AmbiguousClassReference4CE.java"
               options="!ajc">
            <message kind="error" line="9"/>
            <message kind="error" line="10"/>
        </compile>
    </ajc-test>

    <ajc-test dir="errors" title="Crashes when a cast of the form )int) appears"
      keywords="from-errors,purejava,messages-vary">
        <compile files="BadCast.java"
               options="!ajc">
            <message kind="error" line="9"/>
        </compile>
    </ajc-test>

    <ajc-test dir="errors" title="Crashes when the closing brace is reversed"
      keywords="from-errors,purejava,messages-vary">
        <compile files="ClosingBrace.java"
               options="!ajc">
            <message kind="error" line="14"/>
        </compile>
    </ajc-test>

    <ajc-test dir="errors" title="class and interface extension"
      keywords="from-errors,purejava,messages-vary">
        <compile files="BadExtension.java"
               options="!ajc">
            <message kind="error" line="9"/>
            <message kind="error" line="16"/>
            <message kind="error" line="17"/>
            <message kind="error" line="18"/>
            <message kind="error" line="19"/>
            <message kind="error" line="21"/>
            <message kind="error" line="35"/>
            <message kind="error" line="38"/>
        </compile>
    </ajc-test>

    <ajc-test dir="errors" title="illegal synchronized stmts"
      keywords="from-errors,purejava,messages-vary">
        <compile files="BadSynchronized.java"
               options="!ajc">
            <message kind="error" line="3"/>
            <message kind="error" line="4"/>
            <message kind="error" line="5"/>
            <message kind="error" line="6"/>
        </compile>
    </ajc-test>

    <ajc-test dir="new" pr="715" title="incrementing objects, arrays CE"
      keywords="from-resolved_104,purejava,messages-vary">
        <compile files="ArrayIncCE.java"
               options="!ajc">
            <message kind="error" line="15"/>
            <message kind="error" line="16"/>
            <message kind="error" line="17"/>
            <message kind="error" line="18"/>
            <message kind="error" line="19"/>
            <message kind="error" line="20"/>
            <message kind="error" line="21"/>
        </compile>
    </ajc-test>

    <ajc-test dir="pureJava" pr="737"
      title="should have circular inheritance errors (1)"
      keywords="from-resolved_105,purejava,messages-vary">
        <compile files="circle/Test1CF.java"
               options="!ajc">
            <message kind="error" line="7"/>
        </compile>
    </ajc-test>

    <ajc-test dir="pureJava" pr="737"
      title="should have circular inheritance errors (2)"
      keywords="from-resolved_105,purejava,messages-vary">
        <compile files="circle/Test2CF.java"
               options="!ajc">
            <message kind="error" line="6"/>
        </compile>
    </ajc-test>

    <ajc-test dir="pureJava" title="try requires block JLS 14.19"
      keywords="from-resolved_105,purejava,messages-vary">
        <compile files="TryBlockRequiredCE.java"
               options="!ajc">
            <message kind="error" line="6"/>
            <message kind="error" line="7"/>
            <message kind="error" line="8"/>
        </compile>
    </ajc-test>

    <ajc-test dir="pureJava" pr="722" title="loop expressions not declarations"
      keywords="from-resolved_105,purejava,messages-vary">
        <compile files="DeclarationsInLoopsCE.java"
                options="!ajc">
            <message kind="error" line="7"/>
            <message kind="error" line="8"/>
            <message kind="error" line="9"/>
        </compile>
    </ajc-test>

    <ajc-test dir="ng"
      title="array initializers can't have random commas"
      keywords="from-resolved_105,purejava,messages-vary">
        <compile files="ArrayInitError.java"
               options="!ajc,^lenient">
            <message kind="error" line="6"/>
            <message kind="error" line="7"/>
        </compile>
    </ajc-test>

    <ajc-test dir="ng"
      title="array initializers can't have random commas"
      keywords="from-resolved_105,purejava,messages-vary">
        <compile files="ArrayInitError.java"
               options="!ajc,!lenient">
            <message kind="error" line="6"/>
        </compile>
    </ajc-test>

    <ajc-test dir="ng"
      title="try stmt must be block [parser, different lines from javac]"
      keywords="from-resolved_105,purejava,messages-vary">
        <compile files="NonBlockTryStmt.java"
               options="!ajc">
            <message kind="error" line="8"/>
            <message kind="error" line="10"/>
            <message kind="error" line="12"/>
            <message kind="error" line="14"/>
        </compile>
    </ajc-test>

    <ajc-test dir="pureJava"
      title="initializers must be able to complete normally (found by jacks)"
      keywords="from-resolved_105,purejava,messages-vary">
        <compile files="InitializerFlowCf.java"
               options="!ajc">
            <message kind="error" line="1"/>
        </compile>
    </ajc-test>

    <ajc-test dir="new" pr="884" keywords="v1.0"
      title="declare constructor on interface subclasses" >
        <compile options="!ajc" files="DeclareInterfaceConstructor.java"/>
        <run class="DeclareInterfaceConstructor"/>
    </ajc-test>

</suite>

=== abcdefghiklk/fixit/aspectj/org.aspectj/modules/tests/src/org/aspectj/systemtest/model/model.xml
<!DOCTYPE suite SYSTEM "../tests/ajcTestSuite.dtd"[]>

<!-- Model and Hierarchy Tests -->
<suite>
<!-- non-AspectJ 5 specific tests -->

    <ajc-test dir="model/pr77269_1" title="advice in structure model with anonymous inner class">
        <compile files="pack/pr77269.aj" options="-emacssym"/>
    </ajc-test> 

    <ajc-test dir="model/pr77269_2" title="advice in structure model with named inner class">
        <compile files="pr77269b.aj" options="-emacssym"/>
    </ajc-test> 

    <ajc-test dir="model/pr77269_3" title="declare warning in structure model with anonymous inner class">
        <compile files="pack/pr77269c.aj" options="-emacssym">
        	<message kind="warning" line="8" text="blah blah blah"/>
        </compile>
    </ajc-test> 

    <ajc-test dir="model/pr145963_1" title="sourcelocation and jar file">
      <compile files="C.java, SourceAspect.aj" aspectpath="simple.jar" options="-emacssym">
		<message kind="warning" line="6" text="There should be no printlns"/>
	  </compile>
    </ajc-test>

    <ajc-test dir="model/pr145963_2" title="sourcelocation and class file">
      <compile files="C.java, SourceAspect.aj" aspectpath="pkg" options="-emacssym">
		<message kind="warning" line="6" text="There should be no printlns"/>
	  </compile>
    </ajc-test>

   <ajc-test dir="model/pr145963_3" title="aspect in default package">
      <compile files="C.java" aspectpath="simple.jar" options="-emacssym">
		<message kind="warning" line="6" text="There should be no printlns"/>
	</compile>
    </ajc-test>

   <ajc-test dir="model/pr145963_4" title="aspect in java file">
      <compile files="C.java" aspectpath="simple.jar" options="-emacssym">
		<message kind="warning" line="6" text="There should be no printlns"/>
	</compile>
    </ajc-test>
    
    <ajc-test dir="model/pr141730_1" title="new iprogramelement methods">
      <compile files="pr141730.aj" options="-emacssym"/>
    </ajc-test>

	<ajc-test dir="model/pr141730_3" title="ensure aspectpath injar relationships are correct when not filling in model">
      <compile files="MyFoo.java" aspectpath="aspectpath.jar" options="-emacssym"/>
    </ajc-test>

	<ajc-test dir="model/pr148027" title="ensure pcd declare in class appears in model">
      <compile files="A.aj, C.aj" options="-emacssym"/>
    </ajc-test>

	<ajc-test dir="model/pr160469_1" title="ensure advice from abstract aspects appear correctly in the model">
      <compile files="Simple.java" options="-emacssym" aspectpath="aspects.jar"/>
    </ajc-test>

	<ajc-test dir="model/pr160469_2" title="ensure deow from abstract aspects appear correctly in the model">
      <compile files="Simple.java" options="-emacssym" aspectpath="aspects.jar">
		<message kind="warning" line="5" text="warning"/>
      </compile>
    </ajc-test>

<!-- AspectJ 5 specific tests -->

	<ajc-test dir="model/pr115607" title="declare at type appears correctly in structure model">
        <compile files="pr115607.java" options="-1.5,-emacssym"/>
    </ajc-test>

    <ajc-test dir="model/pr131932" title="structure model for generic itd">
        <compile files="pr131932.aj" options="-1.5 -emacssym"/>
    </ajc-test>

    <ajc-test dir="model/pr132130" title="declare annotation appears in structure model when in same file">
        <compile files="pr132130.aj" options="-1.5 -emacssym"/>
    </ajc-test>
    
    <ajc-test dir="model/pr120356" title="@AJ deow appear correctly when structure model is generated">
        <compile files="C.java, A.java" options="-1.5, -emacssym">
         <message kind="error" line="8" text="error"/>
         <message kind="warning" line="5" text="warning"/>
        </compile>
    </ajc-test>

    <ajc-test dir="model/pr143924" title="declare @method relationship">
     <compile files="pr143924.aj" options="-1.5 -showWeaveInfo -emacssym">
        <message kind="weave" text="'public void BankAccount.debit(String,long)' (pr143924.aj:7) is annotated with @Secured"/>
     </compile>
    </ajc-test>
    
    <ajc-test dir="model/pr141730_2" title="new iprogramelement methods for generics">
      <compile files="pr141730.aj" options="-1.5 -emacssym"/>
    </ajc-test>

	<ajc-test dir="model/pr141730_4" title="ensure inpath injar relationships are correct when not filling in model">
      <compile files="MyBar.aj, MyAnnotation.java, NewClass.java" inpath="inpath.jar" options="-1.5 -emacssym">
			<message kind="warning" line="20" text="System.out should not be called"/>
	  </compile>
    </ajc-test>


</suite>
