=== abcdefghiklk/fixit/aspectj/org.aspectj/modules/tests/ajcTestSuite.dtd
<!-- this defines a DOCTYPE for a suite of ajc tests -->
<!-- element-component mappings are in org.aspectj.testing.xml.AjcSpecXmlReader -->
<!-- element names are determined by the component XMLNAME static variable -->

   <!ELEMENT suite (ajc-test*)>
   <!ATTLIST suite suiteDir CDATA #IMPLIED >
	<!-- permits leading inc-compile, will fail -->
   <!ELEMENT ajc-test ((compile | inc-compile | run)*)>
   <!ATTLIST ajc-test title CDATA #REQUIRED >
   <!ATTLIST ajc-test dir CDATA #REQUIRED >
   <!ATTLIST ajc-test pr CDATA #IMPLIED >
   <!ATTLIST ajc-test keywords CDATA #IMPLIED >
   <!ATTLIST ajc-test comment CDATA #IMPLIED >

   <!ELEMENT compile (dir-changes*,message*)>
   <!ATTLIST compile staging CDATA #IMPLIED >
   <!ATTLIST compile badInput CDATA #IMPLIED >
   <!ATTLIST compile files CDATA #IMPLIED >
   <!ATTLIST compile reuseCompiler CDATA #IMPLIED >
   <!ATTLIST compile includeClassesDir CDATA #IMPLIED >
   <!ATTLIST compile argfiles CDATA #IMPLIED >
   <!ATTLIST compile aspectpath CDATA #IMPLIED >
   <!ATTLIST compile classpath CDATA #IMPLIED >
   <!ATTLIST compile extdirs CDATA #IMPLIED >
   <!ATTLIST compile options CDATA #IMPLIED >
   <!ATTLIST compile sourceroots CDATA #IMPLIED >
   <!ATTLIST compile xlintfile CDATA #IMPLIED >
   <!ATTLIST compile outjar CDATA #IMPLIED >

   <!ELEMENT inc-compile (dir-changes*,message*)>
   <!ATTLIST inc-compile tag CDATA #REQUIRED >
   <!ATTLIST inc-compile fresh CDATA #IMPLIED >
   <!ATTLIST inc-compile checkModel CDATA #IMPLIED >

   <!ELEMENT run (dir-changes*,message*)>
   <!ATTLIST run class CDATA #REQUIRED >
   <!ATTLIST run skipTester CDATA #IMPLIED >
   <!ATTLIST run vm CDATA #IMPLIED >
   <!ATTLIST run options CDATA #IMPLIED >
   <!ATTLIST run errStreamIsError CDATA #IMPLIED >
   <!ATTLIST run outStreamIsError CDATA #IMPLIED >
   <!ATTLIST run fork CDATA #IMPLIED >
   <!ATTLIST run vmargs CDATA #IMPLIED >
   <!ATTLIST run aspectpath CDATA #IMPLIED >
   <!ATTLIST run classpath CDATA #IMPLIED >
   <!ATTLIST run LTW CDATA #IMPLIED >
   <!ATTLIST run exception CDATA #IMPLIED >

   <!ELEMENT message (source*)>
   <!ATTLIST message kind (abort | fail | error | warning | info | Xlint) #REQUIRED >
   <!ATTLIST message line CDATA #IMPLIED >
   <!ATTLIST message text CDATA #IMPLIED >
   <!ATTLIST message file CDATA #IMPLIED >
   <!ATTLIST message details CDATA #IMPLIED >

   <!ELEMENT source (#PCDATA)>
   <!ATTLIST source line CDATA #IMPLIED >
   <!ATTLIST source file CDATA #IMPLIED >

   <!ELEMENT dir-changes (#PCDATA)>
   <!ATTLIST dir-changes dirToken (classes | run) #IMPLIED >
   <!ATTLIST dir-changes defaultSuffix (.class) #IMPLIED >
   <!ATTLIST dir-changes added CDATA #IMPLIED >
   <!ATTLIST dir-changes removed CDATA #IMPLIED >
   <!ATTLIST dir-changes updated CDATA #IMPLIED >
   <!ATTLIST dir-changes unchanged CDATA #IMPLIED >
   <!ATTLIST dir-changes expDir CDATA #IMPLIED >
   <!ATTLIST dir-changes fastFail CDATA #IMPLIED >
   <!ATTLIST dir-changes delay CDATA #IMPLIED >

=== abcdefghiklk/fixit/aspectj/org.aspectj/modules/tests/ajcTestsBroken.xml
<!DOCTYPE suite SYSTEM "../tests/ajcTestSuite.dtd">


<suite>

    <ajc-test dir="new" pr="223"
      title="duplicate class names should be signalled by ajc, not javac"
      keywords="from-errors,fail-commandLine"
      comment="XXX harness does not handle per-file errors any more">
        <compile files="DoubleClass1.java,DoubleClass2.java">
            <message kind="error" line="3"  text="DoubleClass1.java:3"/>
            <message kind="error" line="3"  text="DoubleClass2.java:3"/>
        </compile>
    </ajc-test>

    <ajc-test dir="design/around" title="around and return types"
      keywords="from-design,fail-commandLine">
        <compile files="ReturnCastProceed.java,StackChecker.java"/>
        <run class="ReturnCastProceed"/>
    </ajc-test>
    
    <ajc-test dir="new/privilegedAspects"
      title="access to all members of class and inner class from unprivileged aspect"
      keywords="from-resolved_10x,fail-commandLine">
        <compile
          files="driver/UnprivilegedAspect.java,util/Util.java,pack/DefaultTarget.java,pack/PublicTarget.java">
            <message kind="error" line="32"/>
            <message kind="error" line="33"/>
            <message kind="error" line="34"/>
            <message kind="error" line="37"/>
            <message kind="error" line="38"/>
            <message kind="error" line="39"/>
            <message kind="error" line="41"/>
            <message kind="error" line="42"/>
            <message kind="error" line="43"/>
            <message kind="error" line="54"/>
            <message kind="error" line="55"/>
            <message kind="error" line="56"/>
            <message kind="error" line="60"/>
            <message kind="error" line="61"/>
            <message kind="error" line="62"/>
            <message kind="error" line="64"/>
            <message kind="error" line="65"/>
            <message kind="error" line="66"/>
            <message kind="error" line="76"/>
            <message kind="error" line="77"/>
            <message kind="error" line="78"/>
            <message kind="error" line="79"/>
            <message kind="error" line="80"/>
            <message kind="error" line="81"/>
            <message kind="error" line="82"/>
            <message kind="error" line="83"/>
            <message kind="error" line="84"/>
            <message kind="error" line="85"/>
            <message kind="error" line="86"/>
            <message kind="error" line="87"/>
            <message kind="error" line="88"/>
            <message kind="error" line="96"/>
            <message kind="error" line="98"/>
            <message kind="error" line="99"/>
            <message kind="error" line="100"/>
            <message kind="error" line="101"/>
            <message kind="error" line="102"/>
            <message kind="error" line="103"/>
            <message kind="error" line="103"/>
        </compile>
    </ajc-test>

    <ajc-test dir="bugs" pr="33948" 
    		title="default constructor inter-type declaration">
        <compile files="ConstructorDeclaration.java"/>
        <run class="ConstructorDeclaration"/>
    </ajc-test>
</suite>

=== abcdefghiklk/fixit/aspectj/org.aspectj/modules/tests/src/org/aspectj/systemtest/ajc160/parameterAnnotations.xml
<!DOCTYPE suite SYSTEM "../tests/ajcTestSuite.dtd"[]>

<!-- AspectJ v1.6.0 Parameter Annotation Matching Tests -->
<suite>


   <ajc-test dir="features160/parameterAnnotationMatching" title="no xlint for wrong target">
     <compile options="-1.5" files="NonNullAssertionForcer.java"/>
   </ajc-test>

   <ajc-test dir="features160/parameterAnnotationMatching" title="various combinations">
     <compile options="-1.5 -showWeaveInfo" files="TestMatching.aj Anno1.java Anno2.java AnnotatedWithAnno1.java AnnotatedWithAnno2.java">
       <message kind="weave" text="'TestMatching' (TestMatching.aj:4) advised by before advice from 'TestMatching' (TestMatching.aj:3)"/>
       
       <message kind="weave" text="'TestMatching' (TestMatching.aj:7) advised by before advice from 'TestMatching' (TestMatching.aj:6)"/>
       
       <message kind="weave" text="'TestMatching' (TestMatching.aj:11) advised by before advice from 'TestMatching' (TestMatching.aj:10)"/>
       
       <message kind="weave" text="'TestMatching' (TestMatching.aj:16) advised by before advice from 'TestMatching' (TestMatching.aj:15)"/>
       
       <message kind="weave" text="'TestMatching' (TestMatching.aj:22) advised by before advice from 'TestMatching' (TestMatching.aj:21)"/>

       <message kind="weave" text="'TestMatching' (TestMatching.aj:27) advised by before advice from 'TestMatching' (TestMatching.aj:26)"/>
       <message kind="weave" text="'TestMatching' (TestMatching.aj:31) advised by before advice from 'TestMatching' (TestMatching.aj:26)"/>
       
       <message kind="weave" text="'TestMatching' (TestMatching.aj:34) advised by before advice from 'TestMatching' (TestMatching.aj:33)"/>
       
       <message kind="weave" text="'TestMatching' (TestMatching.aj:40) advised by before advice from 'TestMatching' (TestMatching.aj:39)"/>
       <message kind="weave" text="'TestMatching' (TestMatching.aj:41) advised by before advice from 'TestMatching' (TestMatching.aj:39)"/>
       <message kind="weave" text="'TestMatching' (TestMatching.aj:42) advised by before advice from 'TestMatching' (TestMatching.aj:39)"/>
       
       <message kind="weave" text="'TestMatching' (TestMatching.aj:47) advised by before advice from 'TestMatching' (TestMatching.aj:46)"/>
       <message kind="weave" text="'TestMatching' (TestMatching.aj:48) advised by before advice from 'TestMatching' (TestMatching.aj:46)"/>
       
       <message kind="weave" text="'TestMatching' (TestMatching.aj:53) advised by before advice from 'TestMatching' (TestMatching.aj:52)"/>
       <message kind="weave" text="'TestMatching' (TestMatching.aj:54) advised by before advice from 'TestMatching' (TestMatching.aj:52)"/>
       
       <message kind="warning" line="57" text="not been applied"/>
       
       <message kind="weave" text="'TestMatching' (TestMatching.aj:62) advised by before advice from 'TestMatching' (TestMatching.aj:61)"/>
       
     </compile>
   </ajc-test>
   
    <ajc-test dir="features160/parameterAnnotationMatching" title="wildcarded matching">
     <compile options="-1.5 -showWeaveInfo" files="WildcardedMatching.aj Anno1.java Anno2.java AnnotatedWithAnno1.java AnnotatedWithAnno2.java">
       <!-- tbd -->
     </compile>
   </ajc-test>
   
   
   <ajc-test dir="features160/parameterAnnotationMatching" title="various combinations - ctors">
     <compile options="-1.5 -showWeaveInfo" files="TestMatchingCtors.aj Anno1.java Anno2.java AnnotatedWithAnno1.java AnnotatedWithAnno2.java">
       <message kind="weave" text="(TestMatchingCtors.aj:4) advised by before advice from 'TestMatching' (TestMatchingCtors.aj:3)"/>
       
       <message kind="weave" text="(TestMatchingCtors.aj:7) advised by before advice from 'TestMatching' (TestMatchingCtors.aj:6)"/>
       
       <message kind="weave" text="(TestMatchingCtors.aj:11) advised by before advice from 'TestMatching' (TestMatchingCtors.aj:10)"/>
       
       <message kind="weave" text="(TestMatchingCtors.aj:16) advised by before advice from 'TestMatching' (TestMatchingCtors.aj:15)"/>
       
       <message kind="weave" text="(TestMatchingCtors.aj:22) advised by before advice from 'TestMatching' (TestMatchingCtors.aj:21)"/>

       <message kind="weave" text="(TestMatchingCtors.aj:27) advised by before advice from 'TestMatching' (TestMatchingCtors.aj:26)"/>
       <message kind="weave" text="(TestMatchingCtors.aj:31) advised by before advice from 'TestMatching' (TestMatchingCtors.aj:26)"/>
       
       <message kind="weave" text="(TestMatchingCtors.aj:34) advised by before advice from 'TestMatching' (TestMatchingCtors.aj:33)"/>
       
       <message kind="weave" text="(TestMatchingCtors.aj:40) advised by before advice from 'TestMatching' (TestMatchingCtors.aj:39)"/>
       <message kind="weave" text="(TestMatchingCtors.aj:41) advised by before advice from 'TestMatching' (TestMatchingCtors.aj:39)"/>
       <message kind="weave" text="(TestMatchingCtors.aj:42) advised by before advice from 'TestMatching' (TestMatchingCtors.aj:39)"/>
       
       <message kind="weave" text="(TestMatchingCtors.aj:47) advised by before advice from 'TestMatching' (TestMatchingCtors.aj:46)"/>
       <message kind="weave" text="(TestMatchingCtors.aj:48) advised by before advice from 'TestMatching' (TestMatchingCtors.aj:46)"/>
       
       <message kind="weave" text="(TestMatchingCtors.aj:53) advised by before advice from 'TestMatching' (TestMatchingCtors.aj:52)"/>
       <message kind="weave" text="(TestMatchingCtors.aj:54) advised by before advice from 'TestMatching' (TestMatchingCtors.aj:52)"/>
       
       <message kind="warning" line="57" text="not been applied"/>
       
       <message kind="weave" text="(TestMatchingCtors.aj:62) advised by before advice from 'TestMatching' (TestMatchingCtors.aj:61)"/>
       
     </compile>
   </ajc-test>
   
   <ajc-test dir="features160/parameterAnnotationMatching" title="hasmethod">
     <compile options="-1.5 -showWeaveInfo -XhasMember" files="HasMethodMatching.aj Anno1.java Anno2.java AnnotatedWithAnno1.java AnnotatedWithAnno2.java">
       <message kind="weave" text="Extending interface set for type 'Target1' (HasMethodMatching.aj) to include 'java.io.Serializable' (HasMethodMatching.aj)"/>
       <message kind="weave" text="Extending interface set for type 'Target3' (HasMethodMatching.aj) to include 'java.io.Serializable' (HasMethodMatching.aj)"/>
       <message kind="weave" text="Extending interface set for type 'Target4' (HasMethodMatching.aj) to include 'java.io.Serializable' (HasMethodMatching.aj)"/>
     </compile>  
     <run class="HasMethodMatching">
       <stdout>
         <line text="Target1? true"/>
         <line text="Target2? false"/>
         <line text="Target3? true"/>
         <line text="Target4? true"/>
         <line text="Target5? false"/>
       </stdout>
     </run>
   </ajc-test>
   
   <ajc-test dir="features160/parameterAnnotationMatching" title="binary weaving">
     <compile options="-1.5" files="SimpleType.java Anno1.java Anno2.java AnnotatedWithAnno1.java AnnotatedWithAnno2.java AnnotatedWithBoth.java" outjar="code.jar"/>
     <compile options="-1.5 -showWeaveInfo" files="SimpleAspect.java" inpath="code.jar">
        <message kind="weave" text="(SimpleType.java:2) advised by before advice from 'SimpleAspect' (SimpleAspect.java:2)"/>
        <message kind="weave" text="(SimpleType.java:3) advised by before advice from 'SimpleAspect' (SimpleAspect.java:4)"/>
        <message kind="weave" text="(SimpleType.java:4) advised by before advice from 'SimpleAspect' (SimpleAspect.java:6)"/>
        <message kind="weave" text="(SimpleType.java:4) advised by before advice from 'SimpleAspect' (SimpleAspect.java:4)"/>
        <message kind="weave" text="(SimpleType.java:4) advised by before advice from 'SimpleAspect' (SimpleAspect.java:3)"/>
        <message kind="weave" text="(SimpleType.java:5) advised by before advice from 'SimpleAspect' (SimpleAspect.java:5)"/>
        <message kind="weave" text="(SimpleType.java:5) advised by before advice from 'SimpleAspect' (SimpleAspect.java:4)"/>
        <message kind="weave" text="(SimpleType.java:6) advised by before advice from 'SimpleAspect' (SimpleAspect.java:7)"/>
        <message kind="weave" text="(SimpleType.java:6) advised by before advice from 'SimpleAspect' (SimpleAspect.java:6)"/>
        <message kind="weave" text="(SimpleType.java:6) advised by before advice from 'SimpleAspect' (SimpleAspect.java:5)"/>
        <message kind="weave" text="(SimpleType.java:6) advised by before advice from 'SimpleAspect' (SimpleAspect.java:4)"/>
        <message kind="weave" text="(SimpleType.java:6) advised by before advice from 'SimpleAspect' (SimpleAspect.java:3)"/>
        <message kind="weave" text="(SimpleType.java:6) advised by before advice from 'SimpleAspect' (SimpleAspect.java:2)"/>
     </compile>
   </ajc-test>
   
   
</suite>

=== abcdefghiklk/fixit/aspectj/org.aspectj/modules/tests/src/org/aspectj/systemtest/ajc160/annotationValueMatching.xml
<!DOCTYPE suite SYSTEM "../tests/ajcTestSuite.dtd"[]>

<!-- AspectJ v1.6.0 Annotation Value Matching Tests -->
<suite>

   <ajc-test dir="features160/annotationValueMatching" title="enum references - 1">
     <compile options="-1.5 -showWeaveInfo" files="Color.java,TrafficLight.java,Fruit.java,Fruity.java,EnumTest1.java"> 
       <message kind="weave" text="Join point 'method-execution(void a.EnumTest1.m())' in Type 'a.EnumTest1' (EnumTest1.java:9) advised by before advice from 'a.EnumTest1' (EnumTest1.java:13)"/>
       <message kind="weave" text="Join point 'method-execution(void a.EnumTest1.o())' in Type 'a.EnumTest1' (EnumTest1.java:11) advised by before advice from 'a.EnumTest1' (EnumTest1.java:13)"/>
     </compile>
     <run class="a.EnumTest1"/>
   </ajc-test>

   <ajc-test dir="features160/annotationValueMatching" title="enum references - 2">
     <compile options="-1.5 -showWeaveInfo" files="Color.java,TrafficLight.java,Fruit.java,Fruity.java,EnumTest2.java"> 
       <message kind="weave" text="Join point 'method-execution(void a.EnumTest2.m())' in Type 'a.EnumTest2' (EnumTest2.java:9) advised by before advice from 'a.EnumTest2' (EnumTest2.java:13)"/>
       <message kind="weave" text="Join point 'method-execution(void a.EnumTest2.o())' in Type 'a.EnumTest2' (EnumTest2.java:11) advised by before advice from 'a.EnumTest2' (EnumTest2.java:13)"/>
     </compile>
     <run class="a.EnumTest2"/>
   </ajc-test>

   <ajc-test dir="features160/annotationValueMatching" title="enum references - 3">
     <compile options="-1.5 -showWeaveInfo" files="Color.java,TrafficLight.java,Fruit.java,Fruity.java,EnumTest3.java"> 
       <message kind="weave" text="Join point 'method-execution(void a.EnumTest3.m())' in Type 'a.EnumTest3' (EnumTest3.java:9) advised by before advice from 'a.EnumTest3' (EnumTest3.java:13)"/>
     </compile>
     <run class="a.EnumTest3"/>
   </ajc-test>

   <ajc-test dir="features160/annotationValueMatching" title="broken - 1">
     <compile options="-1.5 -showWeaveInfo" files="Broken1.java"> 
       <message kind="error" line="28" text="Invalid annotation value 'a', expected enum value"/>
     </compile>
   </ajc-test>
   
   <ajc-test dir="features160/annotationValueMatching" title="allkinds">
     <compile options="-1.5 -showWeaveInfo" files="AllKinds.java"> 
     </compile>
   </ajc-test>

   <ajc-test dir="features160/annotationValueMatching" title="int value matching">
     <compile options="-1.5 -showWeaveInfo" files="IntValueMatching.java"> 
       <message kind="weave" text="Join point 'method-execution(void IntValueMatching.b())' in Type 'IntValueMatching' (IntValueMatching.java:9) advised by before advice from 'X' (IntValueMatching.java:21)"/>
     </compile>
   </ajc-test>

   <ajc-test dir="features160/annotationValueMatching" title="float value matching">
     <compile options="-1.5 -showWeaveInfo" files="FloatValueMatching.java"> 
       <message kind="weave" text="methodTwo"/>
     </compile>
     <run class="FloatValueMatching"/>
   </ajc-test>

   <ajc-test dir="features160/annotationValueMatching" title="double value matching">
     <compile options="-1.5 -showWeaveInfo" files="DoubleValueMatching.java"> 
       <message kind="weave" text="methodOne"/>
     </compile>
     <run class="DoubleValueMatching"/>
   </ajc-test>

   <ajc-test dir="features160/annotationValueMatching" title="char value matching">
     <compile options="-1.5 -showWeaveInfo" files="CharValueMatching.java"> 
       <message kind="weave" text="methodTwo"/>
     </compile>
     <run class="CharValueMatching"/>
   </ajc-test>

   <ajc-test dir="features160/annotationValueMatching" title="long value matching">
     <compile options="-1.5 -showWeaveInfo" files="LongValueMatching.java"> 
       <message kind="weave" text="methodOne"/>
     </compile>
     <run class="LongValueMatching"/>
   </ajc-test>

   <ajc-test dir="features160/annotationValueMatching" title="string value matching">
     <compile options="-1.5 -showWeaveInfo" files="StringValueMatching.java"> 
       <message kind="weave" text="methodOne"/>
     </compile>
     <run class="StringValueMatching"/>
   </ajc-test>

   <ajc-test dir="features160/annotationValueMatching" title="boolean value matching">
     <compile options="-1.5 -showWeaveInfo" files="BooleanValueMatching.java"> 
       <message kind="weave" text="methodOne"/>
     </compile>
     <run class="BooleanValueMatching"/>
   </ajc-test>

   <ajc-test dir="features160/annotationValueMatching" title="byte value matching">
     <compile options="-1.5 -showWeaveInfo" files="ByteValueMatching.java"> 
       <message kind="weave" text="methodOne"/>
     </compile>
     <run class="ByteValueMatching"/>
   </ajc-test>

   <ajc-test dir="features160/annotationValueMatching" title="short value matching">
     <compile options="-1.5 -showWeaveInfo" files="ShortValueMatching.java"> 
       <message kind="weave" text="methodOne"/>
     </compile>
     <run class="ShortValueMatching"/>
   </ajc-test>

   <ajc-test dir="features160/annotationValueMatching" title="parsing">
     <compile options="-1.5 -showWeaveInfo Parsing.java"/>
   </ajc-test>
      
   <ajc-test dir="features160/annotationValueMatching" title="simple">
     <compile options="-1.5 -showWeaveInfo Simple.java">
       <message kind="weave" text="Join point 'method-execution(void Marked.b())' in Type 'Marked' (Simple.java:18) advised by before advice from 'X' (Simple.java:28)"/>
       <message kind="weave" text="Join point 'method-execution(void Marked.c())' in Type 'Marked' (Simple.java:21) advised by before advice from 'X' (Simple.java:28)"/>
     </compile>       
   </ajc-test>

   <ajc-test dir="features160/annotationValueMatching" title="example one">
     <compile options="-1.5 -showWeaveInfo ExampleOne.java">
       <message kind="weave" text="m002"/>
       <message kind="weave" text="m003"/>
       <message kind="weave" text="m005"/>
     </compile>       
     <run class="ExampleOne">
       <stderr>
         <line text="tracing execution(void ExampleOne.m002())"/>
         <line text="tracing execution(void ExampleOne.m003())"/>
         <line text="tracing execution(void ExampleOne.m005())"/>
       </stderr>
     </run>
   </ajc-test>
   
   <ajc-test dir="features160/annotationValueMatching" title="error case">
     <compile options="-1.5 Error.java">
       <message kind="error" text="Invalid annotation value 'Color.GREEN', expected int value"/>
       <message kind="error" text="Invalid annotation value 'hello', expected float value"/>
       <message kind="error" text="Invalid annotation value 'foo', expected byte value"/>
       <message kind="error" text="Invalid annotation value '123', expected boolean value"/>
       <message kind="error" text="Invalid annotation value '12', expected enum value"/>
       <message kind="error" text="Invalid annotation value '4212312312', expected short value"/>
       <message kind="error" text="Invalid annotation value 'no', expected char value"/>
       <message kind="error" text="Invalid annotation value '30.0f', expected long value"/>
       <message kind="error" text="Invalid annotation value 'foo', expected double value"/>
     </compile>
   </ajc-test>
   
   <ajc-test dir="features160/annotationValueMatching" title="error - non existing value">
     <compile options="-1.5 ErrorOne.java">
       <message kind="error" text="The annotation 'Anno' does not define a value named 'ival'"/>
     </compile>
   </ajc-test>
   
</suite>
