=== abcdefghiklk/fixit/aspectj/org.aspectj/modules/tests/ajcTestSuite.dtd
<!-- this defines a DOCTYPE for a suite of ajc tests -->
<!-- element-component mappings are in org.aspectj.testing.xml.AjcSpecXmlReader -->
<!-- element names are determined by the component XMLNAME static variable -->

   <!ELEMENT suite (ajc-test*)>
   <!ATTLIST suite suiteDir CDATA #IMPLIED >
	<!-- permits leading inc-compile, will fail -->
   <!ELEMENT ajc-test ((compile | inc-compile | run)*)>
   <!ATTLIST ajc-test title CDATA #REQUIRED >
   <!ATTLIST ajc-test dir CDATA #REQUIRED >
   <!ATTLIST ajc-test pr CDATA #IMPLIED >
   <!ATTLIST ajc-test keywords CDATA #IMPLIED >
   <!ATTLIST ajc-test comment CDATA #IMPLIED >

   <!ELEMENT compile (dir-changes*,message*)>
   <!ATTLIST compile staging CDATA #IMPLIED >
   <!ATTLIST compile badInput CDATA #IMPLIED >
   <!ATTLIST compile files CDATA #IMPLIED >
   <!ATTLIST compile reuseCompiler CDATA #IMPLIED >
   <!ATTLIST compile includeClassesDir CDATA #IMPLIED >
   <!ATTLIST compile argfiles CDATA #IMPLIED >
   <!ATTLIST compile aspectpath CDATA #IMPLIED >
   <!ATTLIST compile classpath CDATA #IMPLIED >
   <!ATTLIST compile extdirs CDATA #IMPLIED >
   <!ATTLIST compile options CDATA #IMPLIED >
   <!ATTLIST compile sourceroots CDATA #IMPLIED >
   <!ATTLIST compile xlintfile CDATA #IMPLIED >
   <!ATTLIST compile outjar CDATA #IMPLIED >

   <!ELEMENT inc-compile (dir-changes*,message*)>
   <!ATTLIST inc-compile tag CDATA #REQUIRED >
   <!ATTLIST inc-compile fresh CDATA #IMPLIED >
   <!ATTLIST inc-compile checkModel CDATA #IMPLIED >

   <!ELEMENT run (dir-changes*,message*)>
   <!ATTLIST run class CDATA #REQUIRED >
   <!ATTLIST run skipTester CDATA #IMPLIED >
   <!ATTLIST run vm CDATA #IMPLIED >
   <!ATTLIST run options CDATA #IMPLIED >
   <!ATTLIST run errStreamIsError CDATA #IMPLIED >
   <!ATTLIST run outStreamIsError CDATA #IMPLIED >
   <!ATTLIST run fork CDATA #IMPLIED >
   <!ATTLIST run vmargs CDATA #IMPLIED >
   <!ATTLIST run aspectpath CDATA #IMPLIED >
   <!ATTLIST run classpath CDATA #IMPLIED >
   <!ATTLIST run LTW CDATA #IMPLIED >
   <!ATTLIST run exception CDATA #IMPLIED >

   <!ELEMENT message (source*)>
   <!ATTLIST message kind (abort | fail | error | warning | info | Xlint) #REQUIRED >
   <!ATTLIST message line CDATA #IMPLIED >
   <!ATTLIST message text CDATA #IMPLIED >
   <!ATTLIST message file CDATA #IMPLIED >
   <!ATTLIST message details CDATA #IMPLIED >

   <!ELEMENT source (#PCDATA)>
   <!ATTLIST source line CDATA #IMPLIED >
   <!ATTLIST source file CDATA #IMPLIED >

   <!ELEMENT dir-changes (#PCDATA)>
   <!ATTLIST dir-changes dirToken (classes | run) #IMPLIED >
   <!ATTLIST dir-changes defaultSuffix (.class) #IMPLIED >
   <!ATTLIST dir-changes added CDATA #IMPLIED >
   <!ATTLIST dir-changes removed CDATA #IMPLIED >
   <!ATTLIST dir-changes updated CDATA #IMPLIED >
   <!ATTLIST dir-changes unchanged CDATA #IMPLIED >
   <!ATTLIST dir-changes expDir CDATA #IMPLIED >
   <!ATTLIST dir-changes fastFail CDATA #IMPLIED >
   <!ATTLIST dir-changes delay CDATA #IMPLIED >

=== abcdefghiklk/fixit/aspectj/org.aspectj/modules/tests/incremental/initialTests/selectionTest.xml
<!DOCTYPE suite SYSTEM "../tests/ajcTestSuite.dtd">

<suite >

    <!-- .............................................................................
   	  Should get 1 tests run and passed when running with global options:
   	    -ajctestRequireKeywords=requireKeyword
   	    -ajctestSkipKeywords=skipKeyword
   	    !verbose
   	    -eclipse
   	  
   	  This is used by a JUnit test HarnessSelectionTest.	  
   	  Do not change the outcome without changing that test.
    -->
    
    <ajc-test dir="." title="run and pass" 
    	 keywords="requireKeyword" >
        <compile files="TestNoTester.java"/>
        <run class="TestNoTester"/>
    </ajc-test>

    <!-- .............................................................................
   	  AjcTest should skip or select based on (arbitrary) keywords
    -->

    <ajc-test dir="." pr="100" title="omit if skipKeyword" keywords="requireKeyword,skipKeyword" >
        <compile staging="false" files="TestNoTester.java"/>
        <run class="TestNoTester"/>
    </ajc-test>
    
    <!-- .............................................................................
   	  CompilerRun should resolve soft conflicts in favor of globals. XXX
    -->

    <!-- .............................................................................
   	  CompilerRun should skip hard conflicts (both local and global use force). XXX
    -->
    <ajc-test dir="." pr="101" title="skip - conflict of local ^verbose and global !verbose XXX failing - runs" 
    	 keywords="requireKeyword" >
        <compile files="TestNoTester.java" options="^verbose"/>
        <run class="TestNoTester"/>
    </ajc-test>

    
    <!-- .............................................................................
   	  CompilerRun should skip semantic conflicts - see CompilerRun.Spec.setupArgs(..).
    -->

    <ajc-test dir="." title="skip - local conflict between -lenient, -strict" 
    	 keywords="requireKeyword" >
        <compile files="TestNoTester.java" options="-lenient,-strict"/>
        <run class="TestNoTester"/>
    </ajc-test>

    <ajc-test dir="." title="skip - local conflict between forced lenient, forced strict" 
    	 keywords="requireKeyword" >
        <compile files="TestNoTester.java" options="!lenient,!strict"/>
        <run class="TestNoTester"/>
    </ajc-test>

    <!-- ................... ajc limitations -->
    <ajc-test dir="." title="skip - forced ajc with incremental tests" 
    	 keywords="requireKeyword" >
        <compile staging="true" files="TestNoTester.java" options="!ajc"/>
        <run class="TestNoTester"/>
    </ajc-test>

    <!-- ................... eajc limitations -->
    <ajc-test dir="." title="skip - forced eclipse with -strict" 
    	 keywords="requireKeyword,ajcEclipseForceConflict,eclipseOptionSkip" >
        <compile staging="true" files="TestNoTester.java" options="-strict,!eclipse"/>
        <run class="TestNoTester"/>
    </ajc-test>

    <ajc-test dir="." title="skip - forced eclipse with -lenient" 
    	 keywords="requireKeyword,ajcEclipseForceConflict,eclipseOptionSkip" >
        <compile staging="true" files="TestNoTester.java" options="-lenient,!eclipse"/>
        <run class="TestNoTester"/>
    </ajc-test>

    <ajc-test dir="." title="skip - forced eclipse with forced strict" 
    	 keywords="requireKeyword,ajcEclipseForceConflict,eclipseOptionSkip" >
        <compile staging="true" files="TestNoTester.java" options="!strict,!eclipse"/>
        <run class="TestNoTester"/>
    </ajc-test>

    <ajc-test dir="." title="skip - forced eclipse with forced lenient" 
    	 keywords="requireKeyword,ajcEclipseForceConflict,eclipseOptionSkip" >
        <compile staging="true" files="TestNoTester.java" options="!lenient,!eclipse"/>
        <run class="TestNoTester"/>
    </ajc-test>

    <ajc-test dir="." title="skip - forced eclipse with -preprocess" 
    	 keywords="requireKeyword,ajcEclipseForceConflict,eclipseOptionSkip" >
        <compile staging="true" files="TestNoTester.java" options="-preprocess,!eclipse"/>
        <run class="TestNoTester"/>
    </ajc-test>

    <ajc-test dir="." title="skip - forced eclipse with -usejavac" 
    	 keywords="requireKeyword,ajcEclipseForceConflict,eclipseOptionSkip" >
        <compile staging="true" files="TestNoTester.java" options="-usejavac,!eclipse"/>
        <run class="TestNoTester"/>
    </ajc-test>

    <!-- .............................................................................
   	  CompilerRun should skip invalid options CompilerRun.Spec.INVALID_OPTIONS:
      { "-workingdir", "-argfile", "-sourceroot", "-outjar", "-source" }
    -->

    <ajc-test dir="." title="skip - local invalid option -workingdir" 
    	 keywords="requireKeyword,localInvalidOption" >
        <compile files="TestNoTester.java" options="-workingdir,."/>
        <run class="TestNoTester"/>
    </ajc-test>

    <ajc-test dir="." title="skip - local invalid option -argfile" 
    	 keywords="requireKeyword,localInvalidOption" >
        <compile files="TestNoTester.java" options="-argfile,f"/>
        <run class="TestNoTester"/>
    </ajc-test>

    <ajc-test dir="." title="skip - local invalid option -sourceroot" 
    	 keywords="requireKeyword,localInvalidOption" >
        <compile files="TestNoTester.java" options="-sourceroot,."/>
        <run class="TestNoTester"/>
    </ajc-test>

    <ajc-test dir="." title="skip - local invalid option -outjar"
    	 keywords="requireKeyword,localInvalidOption" >
        <compile files="TestNoTester.java" options="-outjar,foo.jar"/>
        <run class="TestNoTester"/>
    </ajc-test>

    <ajc-test dir="." title="skip - local invalid option -source 1.4" 
    	 keywords="requireKeyword,localInvalidOption" >
        <compile files="TestNoTester.java" options="-source,1.4"/>
        <run class="TestNoTester"/>
    </ajc-test>
    
    <!-- .............................................................................
   	  CompilerRun should skip invalid options specified as globals XXX
    -->

</suite>

=== abcdefghiklk/fixit/aspectj/org.aspectj/modules/tests/src/org/aspectj/systemtest/ajc153/pipelining.xml
<!DOCTYPE suite SYSTEM "../tests/ajcTestSuite.dtd"[]>

<!-- Pipelining tests -->
<suite>

    <!-- testing the very very basics of pipelining -->
    <ajc-test dir="features153/pipelining" title="build two classes">
      <compile files="ClassOne.java,ClassTwo.java" options="-verbose"/>
    </ajc-test>
    
    <!-- testing the basics when an aspect is included, it is placed at the front deliberately -->
    <ajc-test dir="features153/pipelining" title="build one aspect and two classes">
      <compile files="SimpleAspect.java,ClassOne.java,ClassTwo.java" options="-verbose -showWeaveInfo">
        <message kind="weave" text="Join point 'staticinitialization(void SimpleAspect.&lt;clinit&gt;())' in Type 'SimpleAspect' (SimpleAspect.java:1) advised by before advice from 'SimpleAspect' (SimpleAspect.java:2)"/>
        <message kind="weave" text="Join point 'staticinitialization(void ClassOne.&lt;clinit&gt;())' in Type 'ClassOne' (ClassOne.java:1) advised by before advice from 'SimpleAspect' (SimpleAspect.java:2)"/>
        <message kind="weave" text="Join point 'staticinitialization(void ClassTwo.&lt;clinit&gt;())' in Type 'ClassTwo' (ClassTwo.java:1) advised by before advice from 'SimpleAspect' (SimpleAspect.java:2)"/>
      </compile>        
    </ajc-test>
    
    <!-- testing the basics when an aspect is included, aspect should be moved to the front after diet parsing -->
    <ajc-test dir="features153/pipelining" title="build two classes and one aspect">
      <compile files="ClassOne.java,ClassTwo.java,SimpleAspect.java" options="-verbose -showWeaveInfo">
        <message kind="weave" text="Join point 'staticinitialization(void SimpleAspect.&lt;clinit&gt;())' in Type 'SimpleAspect' (SimpleAspect.java:1) advised by before advice from 'SimpleAspect' (SimpleAspect.java:2)"/>
        <message kind="weave" text="Join point 'staticinitialization(void ClassOne.&lt;clinit&gt;())' in Type 'ClassOne' (ClassOne.java:1) advised by before advice from 'SimpleAspect' (SimpleAspect.java:2)"/>
        <message kind="weave" text="Join point 'staticinitialization(void ClassTwo.&lt;clinit&gt;())' in Type 'ClassTwo' (ClassTwo.java:1) advised by before advice from 'SimpleAspect' (SimpleAspect.java:2)"/>
      </compile>        
    </ajc-test>
    
    <!-- just building aspects, no classes around - will the sorting behave -->
    <ajc-test dir="features153/pipelining" title="build two aspects">
      <compile files="SimpleAspect.java,SimpleAspect2.java" options="-verbose -showWeaveInfo">
        <message kind="weave" text="Join point 'staticinitialization(void SimpleAspect.&lt;clinit&gt;())' in Type 'SimpleAspect' (SimpleAspect.java:1) advised by before advice from 'SimpleAspect2' (SimpleAspect2.java:2)"/>
        <message kind="weave" text="Join point 'staticinitialization(void SimpleAspect.&lt;clinit&gt;())' in Type 'SimpleAspect' (SimpleAspect.java:1) advised by before advice from 'SimpleAspect' (SimpleAspect.java:2)"/>
        <message kind="weave" text="Join point 'staticinitialization(void SimpleAspect2.&lt;clinit&gt;())' in Type 'SimpleAspect2' (SimpleAspect2.java:1) advised by before advice from 'SimpleAspect2' (SimpleAspect2.java:2)"/>
        <message kind="weave" text="Join point 'staticinitialization(void SimpleAspect2.&lt;clinit&gt;())' in Type 'SimpleAspect2' (SimpleAspect2.java:1) advised by before advice from 'SimpleAspect' (SimpleAspect.java:2)"/>
      </compile>        
    </ajc-test>
    
    <!-- pointcut in a superclass, subaspect extends the class - pointcut class is supplied after the superclass -->
    <ajc-test dir="features153/pipelining" title="aspect extends class">
      <compile files="ClassOne.java,SubAspect.java,ClassTwo.java,SuperClass.java" options="-verbose -showWeaveInfo">
        <message kind="weave" text="Join point 'staticinitialization(void SubAspect.&lt;clinit&gt;())' in Type 'SubAspect' (SubAspect.java:1) advised by before advice from 'SubAspect' (SubAspect.java:2)"/>
        <message kind="weave" text="Join point 'staticinitialization(void ClassOne.&lt;clinit&gt;())' in Type 'ClassOne' (ClassOne.java:1) advised by before advice from 'SubAspect' (SubAspect.java:2)"/>
        <message kind="weave" text="Join point 'staticinitialization(void ClassTwo.&lt;clinit&gt;())' in Type 'ClassTwo' (ClassTwo.java:1) advised by before advice from 'SubAspect' (SubAspect.java:2)"/>
        <message kind="weave" text="Join point 'staticinitialization(void SuperClass.&lt;clinit&gt;())' in Type 'SuperClass' (SuperClass.java:1) advised by before advice from 'SubAspect' (SubAspect.java:2)"/>
      </compile>        
    </ajc-test>
    
    <!-- testing eclipse to aspectj annotation transformation -->
    <ajc-test dir="features153/pipelining/annotations" title="annotation transformation">
      <compile files="AnAspect.java,Foo.java,DecoratedClass.java" options="-1.5 -verbose"/>
    </ajc-test>

    <!-- does the aspect sorter recognize annotation style aspects, pass the aspects last  -->
    <ajc-test dir="features153/pipelining" title="recognizing annotation style aspects - 1">
      <compile files="ClassOne.java,AtAJAspect.java" options="-1.5 -verbose"/>
    </ajc-test>
    
    <!-- does the aspect sorter recognize annotation style aspects (inner type), pass the aspects last -->
    <ajc-test dir="features153/pipelining" title="recognizing annotation style aspects - 2">
      <compile files="ClassOne.java,AtInnerAJAspect.java" options="-1.5 -verbose"/>
    </ajc-test>
    
    <!-- the aspect is multiple layers down in the class... -->
    <ajc-test dir="features153/pipelining" title="build one class and deeply nested aspect">
      <compile files="ClassOne.java,DeepAspect.java" options="-1.5 -verbose -showWeaveInfo">
        <message kind="weave" text="Join point 'staticinitialization(void ClassOne.&lt;clinit&gt;())' in Type 'ClassOne' (ClassOne.java:1) advised by before advice from 'DeepAspect$Inner$SimpleAspect' (DeepAspect.java:4)"/>
      </compile>
    </ajc-test>
    

</suite>

=== abcdefghiklk/fixit/aspectj/org.aspectj/modules/tests/src/org/aspectj/systemtest/ajc150/ataspectj/misuse.xml
<!DOCTYPE suite SYSTEM "../tests/ajcTestSuite.dtd"[]>

<!-- AspectJ v1.5.0 Tests -->

<suite>

    <ajc-test dir="java5/ataspectj"
        pr="" title="@Aspect class extending @Aspect class">
        <compile files="ataspectj/misuse/Test005.java" options="-1.5 -Xdev:NoAtAspectJProcessing">
        </compile>
    </ajc-test>

    <ajc-test dir="java5/ataspectj"
        pr="" title="class with @Before extending @Aspect class">
        <compile files="ataspectj/misuse/Test006.java" options="-1.5 -Xdev:NoAtAspectJProcessing">
            <message kind="error" line="11" text="class 'Test006B' can not extend aspect"/>
        </compile>
    </ajc-test>

    <comment>a warning. We ignore the pointcut (TBD) - line is enclosing class (TBD Andy do better ?)</comment>
    <ajc-test dir="java5/ataspectj"
        pr="" title="@Pointcut not returning void">
        <compile files="ataspectj/misuse/Test008.java" options="-1.5 -Xdev:NoAtAspectJProcessing">
            <message kind="warning" line="9" text="Found @Pointcut on a method not returning 'void' or not 'public static boolean'"/>
        </compile>
    </ajc-test>

<!--    <ajc-test dir="java5/ataspectj"-->
<!--        pr="" title="@Aspect on interface">-->
<!--        <compile files="ataspectj/misuse/Test010.java" options="-1.5 -Xdev:NoAtAspectJProcessing">-->
<!--            <message kind="warning" line="7" text="Found @Aspect on an interface type 'ataspectj.misuse.Test010'"/>-->
<!--        </compile>-->
<!--    </ajc-test>-->

    <comment>line is enclosing class - TBD</comment>
    <ajc-test dir="java5/ataspectj"
        pr="" title="@Pointcut with garbage string">
        <compile files="ataspectj/misuse/Test014.java" options="-1.5 -Xdev:NoAtAspectJProcessing -Xlint:ignore">
            <message kind="error" line="7" text="Invalid pointcut 'call%dddd"/>
            <message kind="error" text="can't find referenced pointcut"/>
            <message kind="error" text="can't find pointcut"/>
            <message kind="error" text="@AfterThrowing: either 'value' or 'poincut' must be provided, not both"/>
            <message kind="error" text="@AfterReturning: either 'value' or 'poincut' must be provided, not both"/>
            <message kind="error" text="@DeclareWarning used on a non String constant field"/>
            <message kind="error" text="@DeclareError used on a non String constant field"/>
        </compile>
    </ajc-test>

        <comment>line is enclosing class - TBD</comment>
    <ajc-test dir="java5/ataspectj"
        pr="" title="@Pointcut with throws clause">
        <compile files="ataspectj/misuse/Test016.java" options="-1.5 -Xdev:NoAtAspectJProcessing">
            <message kind="warning" line="7" text="Found @Pointcut on a method throwing exception"/>
        </compile>
    </ajc-test>

    <comment>very dirty hack - can't get this location to work properly so added match all error..</comment>
    <comment>amc - with new checks for binding of returning this was giving a different message, so I 
             tweaked the test slightly by swapping the order of the args</comment>
    <ajc-test dir="java5/ataspectj"
        pr="" title="@AfterReturning with wrong number of args">
        <compile files="ataspectj/misuse/Test019.java" options="-1.5 -Xdev:NoAtAspectJProcessing -Xlint:ignore">
            <message kind="error" line="1" text="the parameter x is not bound"/>
            <message kind="error" line="1" text="formal unbound in pointcut"/>
        </compile>
    </ajc-test>

    <comment>line number is enclosing type</comment>
    <ajc-test dir="java5/ataspectj"
        pr="" title="@Before on non-public method">
        <compile files="ataspectj/misuse/Test020.java" options="-1.5 -Xdev:NoAtAspectJProcessing -Xlint:ignore">
            <message kind="error" line="7" text="Found @AspectJ annotation on a non public advice 'someCall()V'"/>
        </compile>
    </ajc-test>

    <comment>line number is enclosing type</comment>
    <ajc-test dir="java5/ataspectj"
        pr="" title="@Before on method not returning void">
        <compile files="ataspectj/misuse/Test021.java" options="-1.5 -Xdev:NoAtAspectJProcessing -Xlint:ignore">
            <message kind="error" line="7" text="Found @AspectJ annotation on a non around advice not returning void 'someCall()I'"/>
        </compile>
    </ajc-test>

    <ajc-test dir="java5/ataspectj"
        pr="" title="@Before with PJP">
        <compile files="ataspectj/misuse/Test100.java" options="-1.5 -Xdev:NoAtAspectJProcessing -Xlint:ignore">
            <message kind="error" text="use of ProceedingJoinPoint is allowed only on around advice"/>
        </compile>
    </ajc-test>

    <!--
ALEX: todo
    <ajc-test dir="java5/ataspectj/coverage"
        pr="" title="@Pointcut with wrong number of args">
        <compile files="ataspectj/misuse/Test022.java" options="-1.5 -Xdev:NoAtAspectJProcessing">
            <message kind="error" line="8" text="int x is not declared in the pointcut parameters"/>
        </compile>
    </ajc-test>

    <ajc-test dir="java5/ataspectj/coverage"
        pr="" title="@Around given an extension of ProceedingJoinPoint">
        <compile files="ataspectj/misuse/Test031.java" options="-1.5 -Xdev:NoAtAspectJProcessing">
            <message kind="error" line="9" text="Is this an error?"/>
        </compile>
    </ajc-test>

    <ajc-test dir="java5/ataspectj/coverage"
        pr="" title="calling @Before advice explicitly as a method">
        <compile files="ataspectj/misuse/Test032.java" options="-1.5 -Xdev:NoAtAspectJProcessing">
            <message kind="error" line="14" text="Advice should never be called explicitly"/>
        </compile>
    </ajc-test>

    <ajc-test dir="java5/ataspectj/coverage"
        pr="" title="@Before on Interface method">
        <compile files="ataspectj/misuse/Test033.java" options="-1.5 -Xdev:NoAtAspectJProcessing">
            <message kind="error" line="4" text="The annotation @Before is disallowed for this location"/>
        </compile>
    </ajc-test>

    <ajc-test dir="java5/ataspectj/coverage"
        pr="" title="@Before and @After on one method">
        <compile files="ataspectj/misuse/Test035.java" options="-1.5 -Xdev:NoAtAspectJProcessing">
            <message kind="error" line="7" text="A method may only be declared as advice once"/>
        </compile>
    </ajc-test>

    <ajc-test dir="java5/ataspectj/coverage"
        pr="" title="@Before advice with empty string">
        <compile files="ataspectj/misuse/Test037.java" options="-1.5 -Xdev:NoAtAspectJProcessing">
        </compile>
    </ajc-test>

    <ajc-test dir="java5/ataspectj/coverage"
        pr="" title="@Pointcut with an empty string">
        <compile files="ataspectj/misuse/Test039.java" options="-1.5 -Xdev:NoAtAspectJProcessing">
        </compile>
    </ajc-test>

    <ajc-test dir="java5/ataspectj/coverage"
        pr="" title="@Before with AND in string">
        <compile files="ataspectj/misuse/Test040.java" options="-1.5 -Xdev:NoAtAspectJProcessing">
        </compile>
    </ajc-test>
-->
</suite>

=== abcdefghiklk/fixit/aspectj/org.aspectj/modules/testing-drivers/testdata/incremental/harness/suite.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE suite SYSTEM "../tests/ajcTestSuite.dtd">

<suite>    

    <!-- driven from JUnit by HarnessSelectionTest.testIncrementalSuite() -->
	<!-- 
	      Using OldAjc (no inc-compile), get two errors (updated file not found (b/c cleared?), 
	      deleted file not found.
	 -->

    <!-- 
         test harness ability to update and delete source files to prep for a compile
     -->
     
    <ajc-test dir="sourceDeleted" title="delete file" keywords="incremental-test" 
      comment="moved to ajcTests{Failing}.xml">
        <compile staging="true" options="-incremental" sourceroots="."/>
        <run class="delete.Main"/>
        <inc-compile tag="20">
            <dir-changes removed="delete.DeleteMe"/>
        	<message kind="error" line="6" file="delete/Target.java"/>
        </inc-compile>
        <inc-compile tag="30"/> 
        <run class="delete.Main"/>
    </ajc-test>
    
    <ajc-test dir="sourceAdded" title="add file with class" keywords="incremental-test" >
        <compile staging="true" options="-incremental" sourceroots="."/>
        <run class="main.Main"/>
        <inc-compile tag="20">
            <dir-changes added="main.Target"/>
        </inc-compile>
        <inc-compile tag="30">
            <dir-changes updated="main.Main"/>
        </inc-compile>
        <run class="main.Main"/>
    </ajc-test>

    <ajc-test dir="defaultPackage" title="do everything in default package" keywords="incremental-test" >
        <compile staging="true"  options="-incremental" sourceroots="."/>
        <run class="Main"/>
        <inc-compile tag="20">
            <dir-changes added="Target"/>
        </inc-compile>
        <run class="Target" skipTester="true"/>
        <inc-compile tag="30">
            <dir-changes updated="Main"/>
        </inc-compile>
        <run class="Main" skipTester="true"/>
        <inc-compile tag="40">
            <dir-changes updated="Main" removed="Target"/>
        </inc-compile>
        <run class="Main"/>
    </ajc-test>

    <!-- 
         test harness detection of .class file added, removed, or changed 
         as a result of the compile process. 
         XXX test dir-changes for JavaRun, CompilerRun
         XXX document special handling of dir-changes paths as FQN for .class suffix
         XXX need negative tests, fails reported
     -->
    <ajc-test dir="classAdded" title="expect class added" keywords="incremental-test" >
        <compile staging="true"  options="-incremental" sourceroots="."/>
        <run class="main.Main"/>
        <inc-compile tag="20" >
            <dir-changes added="main.Target"/>
        </inc-compile>
        <run class="main.Main"  skipTester="true"/>
    </ajc-test>

    <ajc-test dir="classRemoved" title="expect class removed" keywords="incremental-test" >
        <compile staging="true"  options="-incremental" sourceroots="."/>
        <run class="main.Main"/>
        <inc-compile tag="20">
            <dir-changes removed="main.Target"/>
        </inc-compile>
        <run class="main.Main"/>
    </ajc-test>

    <ajc-test dir="classUpdated" title="expect class updated" keywords="incremental-test" >
        <compile staging="true"  options="-incremental" sourceroots="."/>
        <run class="main.Main"/>
        <inc-compile tag="20">
            <dir-changes updated="main.Main"/>
        </inc-compile>
        <run class="main.Main"/>
    </ajc-test>

	<!-- this test cannot work with new AjAttribute.MethodDeclarationLineNumberAttribute attribute
	     since the attribute will be generated for the main method, and has a different reference
	     on each serialization
    <ajc-test dir="expClasses" title="expected class tree" keywords="incremental-test" >
        <compile files="Main.java">
            <dir-changes expDir="exp"/>
        </compile>
        <run class="Main"/>
    </ajc-test>
    -->

</suite>

=== abcdefghiklk/fixit/aspectj/org.aspectj/modules/tests/compilertest.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE suite SYSTEM "../tests/ajcTestSuite.dtd">
<suite>
<ajc-test dir="bugs160/pr173602" title="duplicate itd npe">
<compile files="X.java">
<message kind="error" line="2" text="intertype declaration from "/>
<message kind="error" line="2" text="Duplicate"/>
<message kind="error" line="3" text="intertype declaration from "/>
<message kind="error" line="3" text="Duplicate"/>
<message kind="error" line="6" text="intertype declaration from "/>
</compile>
</ajc-test>
</suite>
